spring.application.name=catalog-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5433/food_delivery
spring.datasource.username=postgres
spring.datasource.password=Arspostgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=catalog

spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.secret=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30


# S3 / DigitalOcean Spaces ? ????????, ???????? ?? ????????
storage.endpoint=https://fra1.digitaloceanspaces.com
storage.region=fra1
storage.access-key=YOUR_ACCESS_KEY
storage.secret-key=YOUR_SECRET_KEY
storage.bucket=YOUR_BUCKET_NAME
storage.base-url=https://YOUR_BUCKET_NAME.fra1.digitaloceanspaces.com

services.order.url=http://localhost:8083