spring.application.name=payment-service
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5433/food_delivery
spring.datasource.username=postgres
spring.datasource.password=Arspostgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=payments

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

jwt.secret=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30
# Freedom Pay
# TODO ???????? ?? ???????? ??????
freedompay.merchant.id=test_merchant
freedompay.secret.key=test_secret_key
freedompay.api.url=https://sandbox.freedompay.kg